### ISSUE TITLE
invalid Objective-C method 0x002e (DW_TAG_subprogram)

### ISSUE THREAD

**Issue by mulle-kybernetik-tv** [Codeon-GmbH/mulle-lldb#8]
Kommt beim debuggen mit mulle_lldb_70 auf linux (mit MulleGLExample). Das Problem war eigentlich schon vor Jahren gefixt...

**Comment by mulle-nat** [comment]
Das passiert im DWARF, wenn die `artificial` parameter nicht richtig erkannt werden (`self`, `_cmd`, `_param`)
